# Generated by Django 4.2.4 on 2023-08-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0002_creditrequest_chargerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargerequest',
            name='status',
            field=models.CharField(choices=[('R', 'REQUESTED'), ('S', 'SUCCESSFUL'), ('F', 'FAILED')], default='R', max_length=1),
        ),
    ]
