# Generated by Django 4.2.4 on 2023-08-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0003_alter_chargerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='charge',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seller',
            name='credit',
            field=models.BigIntegerField(default=0),
        ),
    ]
